library(dplyr)
png("plot3.png", width = 480, height = 480)
Sys.setlocale("LC_TIME", "C")
ower_cons<-read.table(file="household_power_consumption.txt",header=T, sep=";", stringsAsFactors=FALSE)
february_first_sample<-filter(power_cons, Date=="1/2/2007")
february_second_sample<-filter(power_cons, Date=="2/2/2007")
two_days_sample<-rbind(february_first_sample, february_second_sample)
two_days_sample<-na.omit(two_days_sample)
time<-paste(two_days_sample$Date,two_days_sample$Time, sep=" ")
time<-strptime(time, "%d/%m/%Y %H:%M:%S")
plot(time, as.numeric(two_days_sample$Sub_metering_1), xlab = "", ylab = "Energy sub metering", type = "l")
lines(time, as.numeric(two_days_sample$Sub_metering_2), xlab = "", ylab = "Energy sub metering", type = "l", col = "red")
lines(time, as.numeric(two_days_sample$Sub_metering_3), xlab = "", ylab = "Energy sub metering", type = "l", col = "blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=c(1,1,1))
dev.off()