library(dplyr)
png("plot2.png", width = 480, height = 480)
Sys.setlocale("LC_TIME", "C")
ower_cons<-read.table(file="household_power_consumption.txt",header=T, sep=";", stringsAsFactors=FALSE)
february_first_sample<-filter(power_cons, Date=="1/2/2007")
february_second_sample<-filter(power_cons, Date=="2/2/2007")
two_days_sample<-rbind(february_first_sample, february_second_sample)
two_days_sample<-na.omit(two_days_sample)
time<-paste(two_days_sample$Date,two_days_sample$Time, sep=" ")
time<-strptime(time, "%d/%m/%Y %H:%M:%S")
plot(time, as.numeric(two_days_sample$Global_active_power), xlab = "", ylab = "Global Active Power (kilowatts)", type = "l")
dev.off()